# Generated by Django 5.2.4 on 2025-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/", verbose_name="Файл")),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Размер файла (байт)"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Код файла"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Пароль"
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(default=False, verbose_name="Защищен паролем"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Дата истечения")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR код",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество скачиваний"
                    ),
                ),
                (
                    "last_downloaded",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее скачивание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-created_at"],
            },
        ),
    ]
