# Generated by Django 5.2.4 on 2025-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="ID анонимной сессии"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["session_id", "created_at"],
                name="files_file_session_b23d41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["session_id", "expires_at"],
                name="files_file_session_ce65bc_idx",
            ),
        ),
    ]
