# Generated by Django 5.2.4 on 2025-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_file_session_id_file_files_file_session_b23d41_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Файл удален"),
        ),
    ]
